### ISSUE TITLE
OpenVPN/OpenVPNAdapter 开源协议是 AGPL-3.0

### ISSUE THREAD

**Issue by umangoo** [yaooort/OpneVPN#1]
我们知道 OpenVPN/OpenVPNAdapter 开源协议是 AGPL-3.0，只、这是不允许提交到Appstore，您的项目可以提交Appstore吗？

**Comment by yaooort** [comment]
我这边正在试着上 ，现在苹果还没给回复，实在上不去那也没办法。

**Comment by umangoo** [comment]
我正在学习您的项目，自己也试着搭建了openvpn服务器，生成了.ovpn文件使用Tunnelbilck（openvpn的一个PC端客户端）可以正常连接到服务器。现在替换项目中的.ovpn，修改了用户名和密码，修改了Bundle id（包括PacketTunnel的），发现还是连接不上，是不是还有什么细节我没处理？请您指点一下

**Comment by yaooort** [comment]
你有尝试打断点到PacketTunnel里面查看吗？这个项目如果你的.ovpn文件没有问题，是可以连接成功的。

**Comment by umangoo** [comment]
安装一下操作可以调试PacketTunnel了
1、build主程序到设备
2、打上断点
3、Debug → Attach to Process by PID or Name → 填入Network Extension的module name
谢谢 @yaooort 我再看看代码暂时先不关闭帖子
