### ISSUE TITLE
一直连接中

### ISSUE THREAD

**Issue by sysbol** [yaooort/OpneVPN#11]
你好 ，我们的服务器是openConnect 搭建的vpn，服务器提供 用户名，密码，ip 跟端口  没有用认证文件啥的 ，请问opvn 里 该怎么配置 ，请教 谢谢

**Comment by yaooort** [comment]
OpenConnect Server（ocserv）是通过实现Cisco的AnyConnect协议，貌似不能使用OpenVPN协议进行连接

**Comment by sysbol** [comment]
谢谢 请问有anyconnect iOS的demo吗 我没找到

**Comment by yaooort** [comment]
目前貌似没有开源的

**Comment by sysbol** [comment]
谢谢
