### ISSUE TITLE
请问断点不进PacketTunnel是什么原因呢？

### ISSUE THREAD

**Issue by GiggleBro** [yaooort/OpneVPN#16]
楼主你好，已解决的issues我也看过，源码我只改过两个bundleId和appgroup，pid我也是写的PacketTunnel的bundleId。点击连接打印Connection established和正在连接，然后就没有反应了，如果再次点击，一直打印Connection established。在手机设置vpn中status也是正在连接。检查了代码确实发现不了问题在哪，请楼主帮忙解答一下，谢谢了

**Comment by yaooort** [comment]
你好
这个项目好久没看过了
你看下这个[ISS](https://github.com/yaooort/OpenVPN-IOS/issues/4)
或许能够解决你的问题
