### ISSUE TITLE
Internet connection fails if I turn off & turn on Wifi connection

### ISSUE THREAD

**Issue by MSalihBalkan** [yaooort/OpneVPN#3]
Internet connection fails if I turn off & turn on Wifi connection. Steps to reproduce:

1. Connect to VPN
2. Turn off mobile data and Wifi
3. Turn on mobile data or Wifi
4. Try to connect to any server in the internet, for example google.com
Expected result: Connection should be successful
Result: Connection fails to any website on the internet.

**Comment by yaooort** [comment]
You can try to listen to network changes and reconnect at the right time.

**Comment by MSalihBalkan** [comment]
Oh thank you very much for your quick response. I didn't know that I can run code even app has died. "PacketTunnelProvider" class never dies while VPN is active, right? So I can use it to handle auto-reconnect even app is not working in foreground or killed with task manager?

**Comment by MSalihBalkan** [comment]
I tried your suggestion but reconnectAfterTimeInterval is not working. I even tried running it every 10 seconds but no luck. It looks like doesn't do anything. Do you know any other method to restart VPN connection inside PacketTunnelProvider?

**Comment by yaooort** [comment]
Sorry, I tried to use vpn to automatically reconnect after killing the app or connecting to WIFI to disconnect the network.

**Comment by yaooort** [comment]
https://github.com/yaooort/openvpn_ios This is my actual project, but it was written in swift. Please refer to

**Comment by MSalihBalkan** [comment]
reconnect function works there just fine. Thank you very much! :)
