### ISSUE TITLE
why the client is always being connecting when i run it?

### ISSUE THREAD

**Issue by hungrytocode** [yaooort/OpneVPN#7]

**Comment by yaooort** [comment]
你是说，运行过程中一直重连吗？

**Comment by hungrytocode** [comment]
> 你是说，运行过程中一直重连吗？

嗯是的，就是配置之后，self.providerManager.connection.status这个属性一直处于NEVPNStatusConnecting状态连接不上 @yaooort

**Comment by yaooort** [comment]
检查一下你的PacketTunnel是否正常，再看看配置文件

**Comment by hungrytocode** [comment]
> 检查一下你的PacketTunnel是否正常，再看看配置文件

是否正常是什么意思？ 现在是没有提示什么错误，配置文件的话没问题的，因为同一份拿到openvpn官方的app都是ok的

**Comment by yaooort** [comment]
有走到PacketTunnel断点里面调试一下吗？

**Comment by hungrytocode** [comment]
已解决

**Comment by wdq123550** [comment]
怎么解决的？

**Comment by wdq123550** [comment]
同样的问题，怎么解决的，求教大佬啊
