### ISSUE TITLE
老哥，为什么我一点链接，打出的log vpnstatus是马上从正在连接变成断开链接，好像vpn的进程根本没起来

### ISSUE THREAD

**Issue by hungrytocode** [yaooort/OpneVPN#9]

**Comment by hungrytocode** [comment]
我自己创建了一个demo，代码跟你这个一模一样，但每次一点击链接就从正在连接立马变成断开链接

**Comment by yaooort** [comment]
你这样你先确定PacketTunnel 运行了没有，打个断点先

**Comment by hungrytocode** [comment]
我不知道是不是因为哪项我不知道的配置没设，你demo里面的那些bundleid，group，personal vpn，networkextension开关我都有配



    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            陈军称
                            
                            
                                
                                    邮箱：jcchen_1215fox@foxmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


            在2019年01月17日 11:45，Yaooort 写道： 你这样你先确定PacketTunnel 运行了没有，打个断点先



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yaooort/OpenVPN-IOS","title":"yaooort/OpenVPN-IOS","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/yaooort/OpenVPN-IOS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yaooort in #9: 你这样你先确定PacketTunnel 运行了没有，打个断点先"}],"action":{"name":"View Issue","url":"https://github.com/yaooort/OpenVPN-IOS/issues/9#issuecomment-455032089"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/yaooort/OpenVPN-IOS/issues/9#issuecomment-455032089",

"url": "https://github.com/yaooort/OpenVPN-IOS/issues/9#issuecomment-455032089",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by hungrytocode** [comment]
@yaooort 没运行，因为我根本没看到packettunnel这个进程。我不知道是不是哪个配置我没设，但是group，bundle，personal vpn，network extension我都有配了

**Comment by yaooort** [comment]
你先确定能不能走到断点里面，因为这个很重要，如果不能走到断点，就说明你项目配置都有问题。如果能到断点，检查你的vpn配置文件，看格式是否正确就行。
断点打在PacketTunnelProvider第34行

**Comment by hungrytocode** [comment]
@yaooort 不能走到断点里

**Comment by hungrytocode** [comment]
@yaooort 找到原因了，是因为packettunnel的 build phases 中没有添加run script，但是有点不懂run script中的/usr/local/bin/carthage copy-frameworks这一句是干嘛的，我项目中没用到carthage呀

**Comment by yaooort** [comment]
carthage 用来链接OpenVPNAdapter的

**Comment by hungrytocode** [comment]
感谢

**Comment by wanghongenpin** [comment]
> /usr/local/bin/carthage copy-frameworks

老哥，脚本怎么写的

**Comment by hungrytocode** [comment]
您好，我是陈俊城，您的邮件我已收到，如需要请拨打18650345140，谢谢。
